version: "3"

services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: srvwebdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db_create.sql:/docker-entrypoint-initdb.d/db_create.sql
      - ./db_insert.sql:/docker-entrypoint-initdb.d/db_insert.sql
volumes:
  dbdata:
  dbconfig:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "../database"
